import React, { useContext, useEffect } from 'react'
import SongItem from './songitem'
import Spinner from '../layouts/Spinner'
import  SaavnContext  from '../../context/saavn/saavnContext'
import { Row, Col } from 'reactstrap';

function DefaultSongs() {

    const default_songs=[
      {
        "id": "1SfN4dS1",
        "type": "",
        "song": "Maguva Maguva - Male",
        "album": "Vakeel Saab",
        "year": "2020",
        "music": "Thaman S",
        "music_id": "544471",
        "primary_artists": "Sid Sriram",
        "primary_artists_id": "689580",
        "featured_artists": "",
        "featured_artists_id": "",
        "singers": "Sid Sriram",
        "starring": "Pawan Kalyan, Shruti Haasan, Nivetha Thomas, Anjali, Ananya Nagalla",
        "image": "https://c.saavncdn.com/593/Vakeel-Saab-Telugu-2020-20210416213508-500x500.jpg",
        "label": "Aditya Music",
        "albumid": "19533796",
        "language": "telugu",
        "origin": "none",
        "play_count": 25482384,
        "copyright_text": "© 2020 Aditya Music",
        "320kbps": "true",
        "is_dolby_content": false,
        "explicit_content": 0,
        "has_lyrics": "true",
        "lyrics_snippet": "maguwa maguwa lokaniki telusa nee viluva",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyMgz3vn69kCbpX99rzwLWqlxRIdoPtJJ9GKSDSOntf1M0MrYLaW90Ihw7tS9a8Gtq",
        "encrypted_media_path": "NMKyboFo/FhhkEfyw/cYP0JLzvYdI12t7hwKRonZ8rgQkreStCS07b5nJa09ti/l",
        "media_preview_url": "https://preview.saavncdn.com/593/5d46c8ef82c615d2e7c0b938a4df2f05_96_p.mp4",
        "perma_url": "https://www.jiosaavn.com/song/maguva-maguva---male/QTsNf0BUZAI",
        "album_url": "https://www.jiosaavn.com/album/vakeel-saab/QWPc6WXes7I_",
        "duration": "250",
        "rights": {
          "code": 0,
          "reason": "",
          "cacheable": true,
          "delete_cached_object": false
        },
        "cache_state": "false",
        "starred": "false",
        "artistMap": {
          "Thaman S": "544471",
          "Sid Sriram": "689580",
          "Ramajogayya Sastry": "455178",
          "Pawan Kalyan": "461297",
          "Shruti Haasan": "455666",
          "Nivetha Thomas": "1870664",
          "Anjali": "458668",
          "Ananya Nagalla": "8173847"
        },
        "release_date": "2020-03-20",
        "vcode": "010910401138533",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910401094939.mp3",
        "triller_available": false,
        "label_url": "/label/aditya-music-albums/PLNJ90ZqndE_",
        "media_url": "https://aac.saavncdn.com/593/5d46c8ef82c615d2e7c0b938a4df2f05_320.mp4"
    },
    {
        "id": "tNnGg0w3",
        "type": "",
        "song": "Chitti",
        "album": "Jathi Ratnalu",
        "year": "2021",
        "music": "Radhan",
        "music_id": "680011",
        "primary_artists": "Ram Miriyala",
        "primary_artists_id": "6439727",
        "featured_artists": "",
        "featured_artists_id": "",
        "singers": "Ram Miriyala",
        "starring": "Naveen, Rahul, Priyadarshi",
        "image": "https://c.saavncdn.com/272/Jathi-Ratnalu-Telugu-2021-20210307121008-500x500.jpg",
        "label": "Lahari Music",
        "albumid": "25778376",
        "language": "telugu",
        "origin": "none",
        "play_count": 11755552,
        "copyright_text": "℗ 2021 Lahari Recording Company",
        "320kbps": "true",
        "is_dolby_content": false,
        "explicit_content": 0,
        "has_lyrics": "true",
        "lyrics_snippet": "chitti naa bull bull chitti",
        "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyWNsX55SM/A2s4j6b5hg5xolKx2EMMIrTLEIPjWTslN52d04i+SJTLhw7tS9a8Gtq",
        "encrypted_media_path": "NMKyboFo/FhqBgAQc+v2Sn/n1T/q/0ShVXLCnX/UZZbxqE7gM+43Wmbpgo256saV",
        "media_preview_url": "https://preview.saavncdn.com/272/bd094c5de6b428989cd29e4387ccf4f1_96_p.mp4",
        "perma_url": "https://www.jiosaavn.com/song/chitti/BCYFdhMAQAA",
        "album_url": "https://www.jiosaavn.com/album/jathi-ratnalu/Cy60w-cSuy0_",
        "duration": "184",
        "rights": {
            "code": 0,
            "reason": "",
            "cacheable": true,
            "delete_cached_object": false
        },
        "cache_state": "false",
        "starred": "false",
        "artistMap": {
            "Radhan": "680011",
            "Ram Miriyala": "6439727",
            "Ramajogayya Sastry": "455178"
        },
        "release_date": "2021-03-07",
        "vcode": "010910091227744",
        "vlink": "https://jiotunepreview.jio.com/content/Converted/010910091184661.mp3",
        "triller_available": false,
        "label_url": "/label/lahari-music-albums/L899GJu3hlQ_",
        "media_url": "https://aac.saavncdn.com/272/bd094c5de6b428989cd29e4387ccf4f1_320.mp4"
        },        
        {
          "id": "ISDdXTR2",
          "type": "",
          "song": "Jala Jala Jalapaatham",
          "album": "Uppena",
          "year": "2020",
          "music": "Devi Sri Prasad",
          "music_id": "455170",
          "primary_artists": "Jaspreet Jasz, Shreya Ghoshal",
          "primary_artists_id": "465558, 455130",
          "featured_artists": "",
          "featured_artists_id": "",
          "singers": "Jaspreet Jasz, Shreya Ghoshal",
          "starring": "Vaishnav Tej, Krithi Shetty, Vijay Sethupathi",
          "image": "https://c.saavncdn.com/587/Uppena-Telugu-2020-20210218155246-500x500.jpg",
          "label": "Aditya Music",
          "albumid": "19533789",
          "language": "telugu",
          "origin": "none",
          "play_count": 16113253,
          "copyright_text": "© 2020 Aditya Music",
          "320kbps": "true",
          "is_dolby_content": false,
          "explicit_content": 0,
          "has_lyrics": "true",
          "lyrics_snippet": "sell sell selayeruni nenu",
          "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDyFivw9uzUCFBzVSXh8kVBurSuiY6+xoqWWnx0tbynA83lEupgsLi17Bw7tS9a8Gtq",
          "encrypted_media_path": "NMKyboFo/FiZBAY/Hr5oh3TrguZNwjwRjZQHuSYryKBApurpBgXDqJabdZ956tLv",
          "media_preview_url": "https://preview.saavncdn.com/587/a1893d7cea7d5a963c7f411af8e9bbcb_96_p.mp4",
          "perma_url": "https://www.jiosaavn.com/song/jala-jala-jalapaatham-nuvvu/OTsvVSxkZQE",
          "album_url": "https://www.jiosaavn.com/album/uppena/oSAxSArOzUA_",
          "duration": "252",
          "rights": {
            "code": 0,
            "reason": "",
            "cacheable": true,
            "delete_cached_object": false
          },
          "cache_state": "false",
          "starred": "false",
          "artistMap": {
            "Devi Sri Prasad": "455170",
            "Jaspreet Jasz": "465558",
            "Shreya Ghoshal": "455130",
            "Shree Mani": "455176",
            "Panja Vaishnav Tej": "7763038",
            "Krithi Shetty": "7763056",
            "Vijay Sethupathi": "678644"
          },
          "release_date": "2020-03-20",
          "vcode": "010910401226063",
          "vlink": "https://jiotunepreview.jio.com/content/Converted/010910401182893.mp3",
          "triller_available": false,
          "label_url": "/label/aditya-music-albums/PLNJ90ZqndE_",
          "media_url": "https://aac.saavncdn.com/587/a1893d7cea7d5a963c7f411af8e9bbcb_320.mp4"
        },
        {
          "id": "Zj9i9q_L",
          "type": "",
          "song": "Saranga Dariya",
          "album": "Love Story",
          "year": "2020",
          "music": "Pawan Ch",
          "music_id": "7763024",
          "primary_artists": "Mangli",
          "primary_artists_id": "544381",
          "featured_artists": "",
          "featured_artists_id": "",
          "singers": "Mangli",
          "starring": "Naga Chaitanya, Sai Pallavi",
          "image": "https://c.saavncdn.com/582/Love-Story-Telugu-2020-20210325104211-500x500.jpg",
          "label": "Aditya Music",
          "albumid": "19533781",
          "language": "telugu",
          "origin": "none",
          "play_count": 8797858,
          "copyright_text": "© 2020 Aditya Music",
          "320kbps": "true",
          "is_dolby_content": false,
          "explicit_content": 0,
          "has_lyrics": "true",
          "lyrics_snippet": "adi rammante radu ra selia",
          "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy6foJtKSexywalS4CbzClBMVcZdvafr/56gPjFKwfpqjDc53XXuOXmRw7tS9a8Gtq",
          "encrypted_media_path": "NMKyboFo/FgcjYO54oh8nHlgM3exsSTdPTMGYTSEyL+FToEB4KgxYl72/JgF+mSz",
          "media_preview_url": "https://preview.saavncdn.com/582/499f47fee99a0809e9d2b343ac2bec8e_96_p.mp4",
          "perma_url": "https://www.jiosaavn.com/song/saranga-dariya/KgJSWE1BaH8",
          "album_url": "https://www.jiosaavn.com/album/love-story/DWaovElcjpM_",
          "duration": "230",
          "rights": {
            "code": 0,
            "reason": "",
            "cacheable": true,
            "delete_cached_object": false
          },
          "cache_state": "false",
          "starred": "false",
          "artistMap": {
            "Pawan Ch": "7763024",
            "Mangli": "544381",
            "Suddala Ashok Teja": "481323",
            "Akkineni Naga Chaitanya": "455175",
            "Sai Pallavi": "846657"
          },
          "release_date": "2020-03-20",
          "vcode": "010910401240227",
          "vlink": "https://jiotunepreview.jio.com/content/Converted/010910401196670.mp3",
          "triller_available": false,
          "label_url": "/label/aditya-music-albums/PLNJ90ZqndE_",
          "media_url": "https://aac.saavncdn.com/582/499f47fee99a0809e9d2b343ac2bec8e_320.mp4"
        },
        {
            "id": "1UqsPO7u",
            "type": "",
            "song": "Buttabomma",
            "album": "Ala Vaikunthapurramuloo",
            "year": "2019",
            "music": "Thaman S",
            "music_id": "544471",
            "primary_artists": "Armaan Malik",
            "primary_artists_id": "464656",
            "featured_artists": "",
            "featured_artists_id": "",
            "singers": "Armaan Malik",
            "starring": "Allu Arjun, Pooja Hegde, Nivetha Pethuraj",
            "image": "https://c.saavncdn.com/517/Ala-Vaikunthapurramuloo-Telugu-2019-20200116144338-500x500.jpg",
            "label": "Aditya Music",
            "albumid": "17435036",
            "language": "telugu",
            "origin": "none",
            "play_count": 61221500,
            "copyright_text": "© 2020 Aditya Music",
            "320kbps": "true",
            "is_dolby_content": false,
            "explicit_content": 0,
            "has_lyrics": "true",
            "lyrics_snippet": "Buttabomma buttabomma nannu suttukuntive",
            "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDy6cNRQV5rpqCV4BYCV1yJyIhUmSDmawrl4K+qb2UgyflhwcuQJos6BBw7tS9a8Gtq",
            "encrypted_media_path": "NMKyboFo/FgAcS7+Q+RaRRlCSGbgDXmsNWWmtyEkfzRmeCs6VJuktGAX6XN/JUm3",
            "media_preview_url": "https://preview.saavncdn.com/517/68cc88035f2fbcd5772e6551bf64c111_96_p.mp4",
            "perma_url": "https://www.jiosaavn.com/song/buttabomma/QT0aQiR-AEY",
            "album_url": "https://www.jiosaavn.com/album/ala-vaikunthapurramuloo/9w5-ZulMsZc_",
            "duration": "198",
            "rights": {
              "code": 0,
              "reason": "",
              "cacheable": true,
              "delete_cached_object": false
            },
            "cache_state": "false",
            "starred": "false",
            "artistMap": {
              "Thaman S": "544471",
              "Armaan Malik": "464656",
              "Ramajogayya Sastry": "455178",
              "Allu Arjun": "458135",
              "Pooja Hegde": "505220",
              "Nivetha Pethuraj": "1257622"
            },
            "release_date": "2019-09-28",
            "vcode": "010910401085116",
            "vlink": "https://jiotunepreview.jio.com/content/Converted/010910401039350.mp3",
            "triller_available": false,
            "label_url": "/label/aditya-music-albums/PLNJ90ZqndE_",
            "media_url": "https://aac.saavncdn.com/517/68cc88035f2fbcd5772e6551bf64c111_320.mp4"
        },
        {
            "id": "RGM_A92n",
            "type": "",
            "song": "Tharagathi Gadhi",
            "album": "Colour Photo",
            "year": "2020",
            "music": "Kaala Bhairava",
            "music_id": "1941508",
            "primary_artists": "Kaala Bhairava",
            "primary_artists_id": "1941508",
            "featured_artists": "",
            "featured_artists_id": "",
            "singers": "Kaala Bhairava",
            "starring": "Suhas, Sunil, Chandini Chowdary",
            "image": "https://c.saavncdn.com/null/Colour-Photo-Telugu-2020-20201118205906-500x500.jpg",
            "label": "Aditya Music",
            "albumid": "22176015",
            "language": "telugu",
            "origin": "none",
            "play_count": 16280022,
            "copyright_text": "© 2020 Aditya Music",
            "320kbps": "true",
            "is_dolby_content": false,
            "explicit_content": 0,
            "has_lyrics": "true",
            "lyrics_snippet": "targati gadi daati tarlin kathaki",
            "encrypted_media_url": "ID2ieOjCrwfgWvL5sXl4B1ImC5QfbsDypmqY+pt76jkK//Ijun5hHKHl/S/pLwtMcai2ZI62kzTC57AHAVKTFpA80pRr/tHU",
            "encrypted_media_path": "NMKyboFo/FjgYxjQ1sHmDdaxi4FLpdUZdvyUGA0hq73rpkPLDvKywhqQf0x52MZrGBTsxqxbyf8=",
            "media_preview_url": "https://preview.saavncdn.com/null/f131ae51093b978eadbc1b3c3716a8b7_96_p.mp4",
            "perma_url": "https://www.jiosaavn.com/song/tharagathi-gadhi/Ii8mbjUJBV0",
            "album_url": "https://www.jiosaavn.com/album/colour-photo/BVgH0FHXFEs_",
            "duration": "213",
            "rights": {
              "code": 0,
              "reason": "",
              "cacheable": true,
              "delete_cached_object": false
            },
            "cache_state": "false",
            "starred": "false",
            "artistMap": {
              "Kaala Bhairava": "1941508",
              "Kittu Vissapragada": "594972",
              "Suhas": "483998",
              "Sunil": "460901",
              "Chandini chowdary": "889062"
            },
            "release_date": "2020-08-27",
            "vcode": "010910401174519",
            "vlink": "https://jiotunepreview.jio.com/content/Converted/010910401130950.mp3",
            "triller_available": false,
            "label_url": "/label/aditya-music-albums/PLNJ90ZqndE_",
            "media_url": "https://aac.saavncdn.com/null/f131ae51093b978eadbc1b3c3716a8b7_320.mp4"
        }
      ]


    return (
         <div className="row">
            {default_songs.map((song) => {
                return <div className="col-md-4" style={{marginBottom:10}}><SongItem song={song} key={song.id} /></div>
            })}
        </div>
    );
}

const songStyle = {
    display: 'grid',
    gridTemplateColumns: 'repeat(3,1fr)',
    gridGap: '1rem'
}

DefaultSongs.propTypes = {
    
}

export default DefaultSongs
